# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import doctor.video.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=doctor.video.utils.alert_video)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Weight Installation'), (1, 'Food and Hydration Installation'), (2, 'Motion Installation'), (3, 'Sleep Installation'), (4, 'Mind Installation'), (5, 'Welcome'), (6, 'Missing a Day'), (7, 'Failing a Macro'), (8, 'Stop Challenge Choose')], unique=True)),
            ],
            options={
                'verbose_name': 'Video',
                'ordering': ['type'],
                'verbose_name_plural': 'Video',
            },
        ),
    ]
