# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'General'), (1, 'Today'), (3, 'Reminder'), (2, 'Completed'), (4, 'Failed'), (5, 'Badge'), (6, 'Weekly Weight Checkup'), (7, 'One Week Checkup'), (8, 'Two Week Checkup'), (9, 'Three Week Checkup'), (10, 'One Month Checkup'), (11, 'Two Month Checkup')])),
                ('macro_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Weight'), (1, 'Food and Hydration'), (2, 'Motion'), (3, 'Sleep'), (4, 'Mind'), (5, 'Surrounding')], null=True)),
                ('read', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Alerts',
                'ordering': ['read', '-created_at'],
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
