# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Weight Management'), (1, 'Food and Hydration'), (2, 'Motion'), (3, 'Sleep'), (4, 'Mind'), (5, 'Surroundings'), (6, '1 Week Streak'), (7, '2 Week Streak'), (8, '3 Week Streak'), (9, '4 Week Streak'), (10, '5 Week Streak'), (11, '6 Week Streak'), (12, '7 Week Streak'), (13, '8 Week Streak'), (14, 'Perfect Run'), (15, "Sharing's Caring"), (16, 'Influencer')], unique=True)),
            ],
            options={
                'verbose_name': 'Badges',
                'ordering': ['type'],
                'verbose_name_plural': 'Badges',
            },
        ),
    ]
