# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopChallengeChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_video', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Stop Challenge Choose',
                'verbose_name_plural': 'Stop Challenge Choose',
            },
        ),
        migrations.CreateModel(
            name='StopChallengeChooseAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop', models.CharField(max_length=255)),
                ('challenge', models.CharField(max_length=255)),
                ('choose', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessment',
            },
        ),
    ]
