# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_score', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=10, max_digits=14)),
                ('calculation_weight', models.DecimalField(decimal_places=10, editable=False, max_digits=14)),
                ('average_stress_level', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessment',
            },
        ),
        migrations.CreateModel(
            name='MindDailyAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField()),
                ('time_logs', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In Progress'), (1, 'Complete'), (2, 'Incomplete'), (3, 'Reset')])),
                ('assessment_date', models.DateField()),
                ('from_apple_health', models.BooleanField(default=False)),
                ('identify', models.TextField(blank=True)),
                ('choose', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Daily Assessment',
                'verbose_name_plural': 'Daily Assessment',
            },
        ),
        migrations.CreateModel(
            name='MindDaysRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_range', models.PositiveSmallIntegerField()),
                ('end_range', models.PositiveSmallIntegerField()),
                ('required_completions', models.PositiveSmallIntegerField()),
                ('challenge', models.TextField()),
                ('stage', models.PositiveSmallIntegerField()),
                ('help_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Days Range',
                'verbose_name_plural': 'Days Range',
            },
        ),
        migrations.AddIndex(
            model_name='minddaysrange',
            index=models.Index(fields=['start_range', 'stage'], name='mind_mindda_start_r_e2ffde_idx'),
        ),
        migrations.AddField(
            model_name='minddailyassessment',
            name='days_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='mind.MindDaysRange'),
        ),
    ]
