# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mind', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minddailyassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_daily_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mindassessment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mind_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='minddailyassessment',
            index=models.Index(fields=['assessment_date'], name='mind_mindda_assessm_381abc_idx'),
        ),
        migrations.AddIndex(
            model_name='mindassessment',
            index=models.Index(fields=['calculation_weight'], name='mind_mindas_calcula_347ee8_idx'),
        ),
    ]
