# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_auto_20180827_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minddailyassessment',
            options={'ordering': ['day'], 'verbose_name': 'Daily Assessment', 'verbose_name_plural': 'Daily Assessment'},
        ),
    ]
