# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiondailyassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_daily_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motionassessment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motion_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='motiondailyassessment',
            index=models.Index(fields=['assessment_date'], name='motion_moti_assessm_bf09cf_idx'),
        ),
        migrations.AddIndex(
            model_name='motionassessment',
            index=models.Index(fields=['calculation_weight'], name='motion_moti_calcula_6b7db4_idx'),
        ),
    ]
