# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_hydration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodandhydrationdailyassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_and_hydration_daily_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodandhydrationassessment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_and_hydration_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='foodandhydrationdailyassessment',
            index=models.Index(fields=['assessment_date'], name='food_hydrat_assessm_37f58c_idx'),
        ),
        migrations.AddIndex(
            model_name='foodandhydrationassessment',
            index=models.Index(fields=['calculation_weight'], name='food_hydrat_calcula_983a71_idx'),
        ),
    ]
